version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    image: studyexplorer
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=foobarbaz
      - DATABASE_URL=postgres://postgres:postgres@db:5432
    depends_on:
      - db
